version: "3.8"

services:
  frontend:
    build: .
    container_name: application
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./:/app
      - /app/node_modules
    user: node
    links:
      - database
  database:
    build: ./docker/database
    container_name: database
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
